### ISSUE TITLE
Logo Proposal for greed

### ISSUE THREAD

**Issue by area55git** [Steffo99/greed#13]
Hello, I wish to cooperate with **greed**, for this reason I have decided to design a logo for it. If you like this proposal, I can send you the files.

You can suggest the changes you think are necessary.

[![PROPUESTA_DE_LOGO_GREED.jpg](https://s18.postimg.cc/mbgulc549/PROPUESTA_DE_LOGO_GREED.jpg)](https://postimg.cc/image/ju53e2l7p/)

**Comment by area55git** [comment]
Do you accept my logo proposal?
to send you the original files by Drive.

**Comment by Steffo99** [comment]
Sorry to keep you waiting!
Since this is my project for the final exam, I don't want to accept contributions until the exam is finished, so I must **reject** this proposal.

---

I see that you're opening issues in a lot of other GitHub projects.
Instead of opening so many issues in random open source projects, where they may be rejected, I'd suggest looking at the [list of projects that currently need help](https://github.com/search?q=label%3A%22help+wanted%22&state=open&type=Issues).

**Comment by area55git** [comment]
Hello, thank you very much for answering, I'm really new to github, I'm a graphic designer and I do not know how to program, I can only contribute in this area, I'm going to continue researching and learning. I would appreciate any guidance.
