### ISSUE TITLE
Implementing Message Queue

### ISSUE THREAD

**Issue by syafiquel** [Steffo99/greed#142]
The bot is currently getting message updates from getUpdates method in Bot class instead of Updater class. I wanted to implement MessageQueue but as far as I know it can be used through Updater class. My question is it possible for me to add MessageQueue to the current getUpdates approach from the Bot i am using?

**Comment by Steffo99** [comment]
Do you mean this [`MessageQueue`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.messagequeue.html)?

It's deprecated (python-telegram-bot/python-telegram-bot#2139), it doesn't seem a good idea to me...

In any case, I think refactoring the bot to use an Updater instead of my custom framework might be possible...  
Perhaps editing `core.py` might be enough?

**Comment by syafiquel** [comment]
> Do you mean this [`MessageQueue`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.messagequeue.html)?
> 
> It's deprecated ([python-telegram-bot/python-telegram-bot#2139](https://github.com/python-telegram-bot/python-telegram-bot/issues/2139)), it doesn't seem a good idea to me...
> 
> In any case, I think refactoring the bot to use an Updater instead of my custom framework might be possible...
> Perhaps editing `core.py` might be enough?

Yeah I am thinking so but then I just discovered a way to add MessageQueue object wtihout changing the codebase. In my use case it probably might work even though is is now deprecated, Thank you.
