### ISSUE TITLE
NFT rule 34 broodmother

### ISSUE THREAD

**Issue by Gattopardo00** [Steffo99/greed#165]
## Describe the feature

If you play doto best dota2 with me , I'll give you a rare NFT of broodmother that sprays her web from her nipples on your gyro

## Reasoning for the implementation

Because I wanna rank with you 

## Additional information

Please contact me by SMS or on my Game Ranger account named "Gattopardo"

**Comment by Gimbardo** [comment]
# This is some real shit
I need this to be fixed **ASAP**, or else i wont be able to see those cute long legs anymore.  
## Reasons why you should fix this
If your code doesn't have some cool dota rankedinos in it, it probably won't ever be used. And you need these cool NFTs, with long black *legs* in order to make it a **DOTINO VELOCE**.  
## The Plan
| Player | Role | Hero |
|--------|------|-------|
| @Gattopardo00  |SafeLane Carry| Omniknight|
| @Steffo99 | Midlane | IO (aka Wisp) |
| @me | Primary Support | Tusky Duski |
| @max | Offlane | Clockwerk |
| random guy | Secondary Support | AntiMage (because yes) |

## Conclusion
i need some zzz
